title: 'rest@rea'
url: 'https://morningdip.github.io'
baseurl: ''

repository:  morningdip/morningdip.github.io
repository_branch: main

favicon: ./assets/images/favicon.svg
favicon_dark: ./assets/images/favicon-dark.svg

header_pages:
  - index.md
  - about.md
  - contact.md

style: dark

plugins:
  - jekyll-feed
  - jekyll-seo-tag
