title: 'rest@rea'
url: 'https://morningdip.github.io'
baseurl: ''

repository:  morningdip/morningdip.github.io
repository_branch: main


header_pages:
  - index.md
  - about.md
  - contact.md

style: dark

plugins:
  - jekyll-feed
  - jekyll-seo-tag
